---
kind: pipeline
type: docker
name: Build
steps:
- name: build
  image: node:16.0.0
  commands:
    - npm config set registry https://registry.npmmirror.com
    - npm i -g pnpm
    - pnpm i
    - pnpm build

---
kind: pipeline
type: exec               
name: Mirror
steps:
- name: gitee
  commands:
    - git push --mirror git@gitee.com:alvisisme/$DRONE_REPO_NAME
- name: github
  commands:
    - git push --mirror git@github.com:alvisisme/$DRONE_REPO_NAME
